model:
  onnx_path: saved_models/combined/ResNet18_GMVAE_robust_mb_2.onnx
  input_shape: [-1, 8]
specification:
  vnnlib_path: vnnlibs/safe_encodings_8_robust_mb_2_phi_2.vnnlib
solver:
  batch_size: 2000
  alpha-crown:
    iteration: 100
    lr_alpha: 0.1
bab:
  timeout: 2000
  branching:
    reduceop: min
    method: fsb
    candidates: 50
attack:
  pgd_steps: 50000
  pgd_restarts: 50
